### PR TITLE
WIP: Implement Messenger-friendly search

### PR DESCRIPTION
**Pull request by qwertyuu**
I will be adding the equivalent of
image
this searchbox directly into fbchat so that projects like [mine](https://github.com/qwertyuu/SMSenger-Bridge) will be able to search in both the user's messenger AND facebook contacts (and even more?)

Whis is a very important feature, because at the moment the best way I found was: enumerate all current threads and search in them. That means, if you have not talked to a contact in a while and it is a messenger-only account that you are searching, the graph-api search will not return a result for that contact (the graph api uses only facebook accounts as results)... but this search box does!

I am just getting the hang of the codebase here, I am far from done (hence the `WIP:` prefix)

### CODE REVIEW

**Comment by qwertyuu** [comment]
How to get that box:
1. Send some multimedia content
1. Press "share"
1. voilà!

If you open a browser inspection window and go to network when typing in the field, you will clearly see some queries made to `graphsqlbatch` endpoint.

**Comment by qwertyuu** [comment]
TODOs (if anyone wants to hint me so I learn about the project a little faster, let's go!)

- [ ] Find where client environment variables are setup so I can run tests
- [ ] Setup a test for easier development (TDD)
- [ ] Integrate call to graphql
- [ ] Treat output accordingly
- [ ] Add method in client for easy access
- [ ] Write more tests
- [ ] Update this PR

**Comment by madsmtm** [comment]
Thanks for the initiative!

I think most of the test suite is broken, so you don't have to worry too much about that for now. But if you do want to set it up locally, you first need two Facebook accounts, see [CONTRIBUTING.rst](https://github.com/carpedm20/fbchat/blob/master/CONTRIBUTING.rst).

And maybe you can share some example request/response data to and from the endpoint?

**Comment by qwertyuu** [comment]
```
https://www.messenger.com/api/graphqlbatch/?dpr=1
```
`POST parameter` | `POST value` (Request)
```
__a | 1
__be | -1
__dyn | 7AzkXh8OByKEjgDxKy1l0BwRAKGgS8USQjFwgoqzob4q2i5U4e2CGwEyFojyR88xK5WAAzoOuVWxeUW2y4GDxq2WdxK4rzoKjG2e5UC4bzazp8nwkEG9KewBx66E4zwxUvgeFUlF3FK5ES2G2Z5wlUf8Cu4rG7pE9GBy8pxO12xm5oCbx-2KdyU4e4e6efKfK8hobHwyzUR1Gicyo94dK5ocUSh3UOGyprxCfxKaK5EO2G2WGDwHx-ey8O8KuV8y2G2C9hEKUdUyfKUy2m6UK6UozArwzgK7o
__pc | PHASED:messengerdotcom_pkg
__req | 8u
__rev | 4516693
__user | 100000693858127
fb_dtsg | AQGZQXwKuI0r:AQGeAND9OjJf
jazoest | 265817190818811975117734811458658171101657868577910674102
queries | {"o0":{"doc_id":"1746741182112617","query_params":{"search_query":"fbchat","result_limit":5,"messenger_commerce":true,"include_games":true,"internal_bot":false,"vc_endpoint":false}}}
```

Response (as you can see, it has multiple lines of valid json, but the Response itself is NOT valid json)

```
{"o0":{"data":{"entities_named":{"id":"c3JjaF9lbnRzOmZiY2hhdA==","search_results":{"edges":[{"subtext":null,"node":{"id":"1220091511342800","name":"FBChatBot","profile_picture":{"uri":"https:\/\/scontent.fyhu2-1.fna.fbcdn.net\/v\/t1.0-1\/c5.0.32.32\/p32x32\/13938534_1220091821342769_2001829699704659541_n.jpg?_nc_cat=105&_nc_ht=scontent.fyhu2-1.fna&oh=3fe3db96ff2a16a489667759d192611e&oe=5C3BFB5F"},"url":"https:\/\/www.facebook.com\/FBChatBot-1220091511342800\/","is_messenger_user":true,"category_type":"COMPUTER_COMPANY","is_verified":false}},{"subtext":null,"node":{"id":"1988012271433292","name":"Fbchatbot","profile_picture":{"uri":"https:\/\/scontent.fyhu2-1.fna.fbcdn.net\/v\/t1.0-1\/p32x32\/20258499_1988447368056449_6217087630690630133_n.jpg?_nc_cat=107&_nc_ht=scontent.fyhu2-1.fna&oh=ce54398e28436d73cbe949786ac39321&oe=5C7C887F"},"url":"https:\/\/www.facebook.com\/Fbchatbot-1988012271433292\/","is_messenger_user":true,"category_type":"APP","is_verified":false}},{"subtext":null,"node":{"id":"1317267691628454","name":"Fbchatbot","profile_picture":{"uri":"https:\/\/scontent.fyhu2-1.fna.fbcdn.net\/v\/t1.0-1\/p32x32\/23755723_1670816312940255_7923192228618851772_n.png?_nc_cat=110&_nc_ht=scontent.fyhu2-1.fna&oh=e5015e1b86fe5f4f4137944663bb3ca9&oe=5C753D7B"},"url":"https:\/\/www.facebook.com\/uzletichatbot\/","is_messenger_user":true,"category_type":"WEBSITE","is_verified":false}},{"subtext":null,"node":{"id":"1941964506016838","name":"FBchatbotservice","profile_picture":{"uri":"https:\/\/scontent.fyhu2-1.fna.fbcdn.net\/v\/t1.0-1\/p32x32\/19510590_1941964559350166_2986522728579071738_n.png?_nc_cat=100&_nc_ht=scontent.fyhu2-1.fna&oh=ac38e42eabe0b3d4b960b60ba23ed81f&oe=5C6D1788"},"url":"https:\/\/www.facebook.com\/chatbotservice\/","is_messenger_user":true,"category_type":"COMPUTER_COMPANY","is_verified":false}},{"subtext":null,"node":{"id":"471647423347205","name":"FB-Chatbots","profile_picture":{"uri":"https:\/\/scontent.fyhu2-1.fna.fbcdn.net\/v\/t1.0-1\/p32x32\/43151016_478114126033868_8851059824683646976_n.png?_nc_cat=111&_nc_ht=scontent.fyhu2-1.fna&oh=6843280fb5312acdd333fefec15d26f6&oe=5C832A3C"},"url":"https:\/\/www.facebook.com\/messenger.chatbots.agency\/","is_messenger_user":true,"category_type":"INTERNET_MARKETING_SERVICE","is_verified":false}}]}}}}}
{
   "successful_results": 1,
   "error_results": 0,
   "skipped_results": 0
}
```

**Comment by madsmtm** [comment]
Thanks for the quick response.

I've already had to deal with requests to `/api/graphqlbatch` a lot, so I built `/client.py:Client.graphql_request` and `/graphql.py:GraphQL`, that help dealing with the annoying output. To get your result, something as simple as:
```py
# This parameter data is taken from your comment
query_params = {
    "search_query": "fbchat",
    "result_limit": 5,
    "messenger_commerce": True,
    "include_games": True,
    "internal_bot": False,
    "vc_endpoint": False
}
# The `doc_id` is taken from your comment
j = client.graphql_request(GraphQL(doc_id=1746741182112617, params=query_params)
```
Would give you:
```json
{
  "entities_named": {
    "id": "[REDACTED]",
    "search_results": {
      "edges": [
        {
          "node": {
            "category_type": "[REDACTED]",
            "id": "[REDACTED]",
            "is_messenger_user": true,
            "is_verified": false,
            "name": "[REDACTED]",
            "profile_picture": {
              "uri": "[REDACTED]"
            },
            "url": "[REDACTED]"
          },
          "subtext": null
        },
        ...
      ]
    }
  }
}
```
The difficult part is now to parse the output, and get `Thread`s out. Have a look at the `/graphql.py:graphql_to_X` functions, maybe you can extend some of them. Also, have a look at what's possible with the `query_params`, these input options looks quite interesting

**Pull request closed without merging**
